import { Component, EventEmitter, Input, OnDestroy, Output, TemplateRef, ViewChild, inject } from '@angular/core';
import { MatButtonModule } from '@angular/material/button';
import { MatDialog, MatDialogModule, MatDialogRef } from '@angular/material/dialog';
import type { Meta, StoryObj } from '@storybook/angular';
import { fn } from 'storybook/test';
@Component({ selector: 'app-dialog-demo', standalone: true, imports: [MatButtonModule, MatDialogModule], template: `<button matButton="filled" type="button" (click)="open()">{{ buttonLabel }}</button><ng-template #content><h2 mat-dialog-title>{{ heading }}</h2><mat-dialog-content><p>{{ description }}</p></mat-dialog-content><mat-dialog-actions align="end"><button matButton="text" mat-dialog-close="cancel">Cancel</button><button matButton="filled" [mat-dialog-close]="'confirm'">{{ confirmLabel }}</button></mat-dialog-actions></ng-template>` })
class DialogDemoComponent implements OnDestroy { @Input() buttonLabel = 'Delete draft'; @Input() heading = 'Delete this draft?'; @Input() description = 'This example only reports your choice; no draft is deleted.'; @Input() confirmLabel = 'Delete'; @Output() result = new EventEmitter<string>(); @ViewChild('content', { static: true }) content!: TemplateRef<unknown>; private readonly dialog = inject(MatDialog); private ref?: MatDialogRef<unknown, string>; open(): void { this.ref = this.dialog.open(this.content, { ariaLabel: this.heading }); this.ref.afterClosed().subscribe((value) => { if (value) this.result.emit(value); }); } ngOnDestroy(): void { this.ref?.close(); } }
const meta = { title: 'Material/Dialog', component: DialogDemoComponent, tags: ['autodocs'], parameters: { layout: 'padded' }, args: { result: fn() }, argTypes: { buttonLabel: { control: 'text' }, heading: { control: 'text' }, description: { control: 'text' }, confirmLabel: { control: 'text' }, result: { control: false } } } satisfies Meta<DialogDemoComponent>;
export default meta; type Story = StoryObj<DialogDemoComponent>; export const Confirmation: Story = {}; export const LongContent: Story = { args: { heading: 'Archive monthly statements?', description: 'Archived statements remain available in your account history. This example is a safe demonstration and does not change any account data.', confirmLabel: 'Archive' } };
